GET http://localhost:8000/categories/

###
GET http://localhost:8000/categories/0996bc9a-3a4d-4ff7-8191-e4ea63c4aa3a/

###
POST http://localhost:8000/categories/
Content-Type: application/json

{
    "name": "Movie"
}

###
PUT http://localhost:8000/categories/0996bc9a-3a4d-4ff7-8191-e4ea63c4aa3a/
Content-Type: application/json

{
    "name": "Moviess",
    "description": "some description",
    "is_active": false
}