version: '3'

services:
  app:
    build: .
    container_name: codeflix-micro-videos-python-app
    volumes:
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/python/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/python/zsh:delegated
